name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  build_release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: npm install

      - name: Build portable executable
        run: npx tauri build --no-bundle

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: src-tauri/target/release/winget-portable.exe
          name: "Winget ${{ github.ref_name }}"
          body: "Automatic portable version."
          draft: false
          prerelease: false
